/*
 * generated by Xtext
 */
package org.xmdlab.dsl.puppet.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PuppetDslUiModule extends org.xmdlab.dsl.puppet.ui.AbstractPuppetDslUiModule {
	public PuppetDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
