/*
 * generated by Xtext
 */
package org.xmdlab.dsl.puppet.validation

import org.eclipse.xtext.validation.Check
import org.xmdlab.dsl.puppet.puppetDsl.DslNode
import org.xmdlab.dsl.puppet.puppetDsl.DslRole
import org.xmdlab.dsl.puppet.puppetDsl.PuppetDslPackage

import static org.xmdlab.dsl.puppet.validation.IssueCodes.*

import static extension java.lang.Character.*

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class PuppetDslValidator extends AbstractPuppetDslValidator {

	public static val INVALID_NAME = 'invalidName'

	@Check
	def checkDslNodeNameStartsWithCapital(DslNode dslNode) {
		if (dslNode.name.charAt(0).upperCase)
			warning("DslNode name should start with a lower case letter", PuppetDslPackage::eINSTANCE.dslNode_Name,
				UNCAPITALIZED_NAME, dslNode.name)
	}

	@Check
	def checkDslNodeDomain(DslNode dslNode) {
		if (dslNode.domain.indexOf('') > 0)
			warning("DslNode domain should be a domain name like e.g.: mydomain.com",
				PuppetDslPackage::eINSTANCE.dslNode_Domain, NO_DOMAIN_EXPRESSION, dslNode.domain)
	}

	@Check
	def checkDslRoleNameStartsWithCapital(DslRole dslRole) {
		if (dslRole.name.charAt(0).upperCase)
			warning("DslRole name should start with a lower case letter", PuppetDslPackage::eINSTANCE.dslRole_Name,
				UNCAPITALIZED_NAME, dslRole.name)
	}

//	@Check
//	def checkDslProfileNameStartsWithCapital(DslProfile dslProfile) {
//		if (dslProfile.name.charAt(0).upperCase)
//			warning("DslProfile name should start with a lower case letter", PuppetDslPackage::eINSTANCE.dslProfile_Name,
//				UNCAPITALIZED_NAME, dslProfile.name)
//	}
//	
//	@Check
//	def checkDslModuleNameStartsWithCapital(DslModule dslModule) {
//		if (dslModule.name.charAt(0).upperCase)
//			warning("DslModule name should start with a lower case letter", PuppetDslPackage::eINSTANCE.dslModule_Name,
//				UNCAPITALIZED_NAME, dslModule.name)
//	}
}
