/*
 * generated by Xtext
 */
package org.xmdlab.cartridge.generator.dsl.ui.contentassist

import org.xmdlab.cartridge.generator.dsl.ui.contentassist.AbstractCartridgeDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class CartridgeDslProposalProvider extends AbstractCartridgeDslProposalProvider {
}
