/*
 * generated by Xtext
 */
package org.xmdlab.cartridge.generator.dsl;

import org.eclipse.xtext.util.Modules2;
import org.xmdlab.cartridge.generator.dsl.generator.CartridgeGeneratorModule;

import com.google.inject.Guice;
import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages without equinox extension
 * registry
 */
public class CartridgeDslStandaloneSetup extends
		CartridgeDslStandaloneSetupGenerated {

	public static void doSetup() {
		new CartridgeDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}

	@Override
	public Injector createInjector() {
		Injector injector = Guice.createInjector(Modules2
				.mixin(new CartridgeDslRuntimeModule(),
						new CartridgeGeneratorModule()));
		return injector;
	}
}
