/**
 * Generated by Xgen. !!! DO NOT EDIT BY HAND IF THIS FILE WAS GENERATED TO A DERIVED DIRECTORY !!!
 * Xtend Template: org.xmdlab.cartridge.generator.dsl.templates.templates.TemplateTpl
 */
package org.xmdlab.cartridge.puppet.templates

import org.xmdlab.cartridge.puppet.metafacade.*

class RoleBaseTpl extends RoleBaseTplBase {
	
	override doGenerate(NodeMetafacade nodeMetafacade) '''
	class role {
	  include profile::base
	}	
	'''
}
