/*
* generated by Xtext
*/
package org.xmdlab.dsl.application;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ApplicationDslStandaloneSetup extends ApplicationDslStandaloneSetupGenerated {

	public static void doSetup() {
		new ApplicationDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

