/*
 * generated by Xtext
 */
package org.xmdlab.dsl.application;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ApplicationDslRuntimeModule extends org.xmdlab.dsl.application.AbstractApplicationDslRuntimeModule {

}
