/*
 * generated by Xtext
 */
package org.xmdlab.cartridge.generator.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.generator.IOutputConfigurationProvider;
import org.xmdlab.cartridge.generator.dsl.io.CartridgeOutputsConfigurationProvider;

import com.google.inject.Binder;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CartridgeDslUiModule extends
		org.xmdlab.cartridge.generator.dsl.ui.AbstractCartridgeDslUiModule {

	public CartridgeDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	@Override
	public void configure(Binder binder) {
		super.configure(binder);
		binder.bind(IOutputConfigurationProvider.class).to(
				CartridgeOutputsConfigurationProvider.class);
		// binder.bind(JavaIoFileSystemAccess.class).to(
		// OutputConfigurationAwareFileSystemAccess.class);
	}
}
