/*
 * generated by Xtext
 */
package org.xmdlab.dsl.domain.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DomainDslUiModule extends org.xmdlab.dsl.domain.ui.AbstractDomainDslUiModule {
	public DomainDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
