/*
 * generated by Xtext
 */
package org.xmdlab.dsl.puppet.ui.contentassist

import org.xmdlab.dsl.puppet.ui.contentassist.AbstractPuppetDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class PuppetDslProposalProvider extends AbstractPuppetDslProposalProvider {
}
