/**
 * Generated by Xgen. !!! DO NOT EDIT BY HAND IF THIS FILE WAS GENERATED TO A DERIVED DIRECTORY !!!
 * Xtend Template: org.xmdlab.cartridge.generator.dsl.templates.metafacade.MetafacadeXtendTpl
 */
package org.xmdlab.cartridge.common.metafacade

interface Metafacade<T> {
	def T getModelResource()
	def void setModelResource(T modelResource)
}
