/*
 * generated by Xtext
 */
package org.xmdlab.dsl.domain.ui.contentassist

import org.xmdlab.dsl.domain.ui.contentassist.AbstractDomainDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class DomainDslProposalProvider extends AbstractDomainDslProposalProvider {
}
