/**
 * generated by Xtext
 */
package org.xmdlab.dsl.puppet.validation;

import org.eclipse.xtext.validation.Check;
import org.xmdlab.dsl.puppet.validation.AbstractPuppetDslValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class PuppetDslValidator extends AbstractPuppetDslValidator {
  public final static String INVALID_NAME = "invalidName";
  
  @Check
  public void checkDslNodeNameStartsWithCapital(final /* DslNode */Object dslNode) {
    throw new Error("Unresolved compilation problems:"
      + "\nPuppetDslPackage.eINSTANCE cannot be resolved to a type."
      + "\nname cannot be resolved"
      + "\ncharAt cannot be resolved"
      + "\nupperCase cannot be resolved"
      + "\neINSTANCE cannot be resolved"
      + "\ndslNode_Name cannot be resolved"
      + "\nname cannot be resolved");
  }
  
  @Check
  public void checkDslNodeDomain(final /* DslNode */Object dslNode) {
    throw new Error("Unresolved compilation problems:"
      + "\nPuppetDslPackage.eINSTANCE cannot be resolved to a type."
      + "\ndomain cannot be resolved"
      + "\nindexOf cannot be resolved"
      + "\n> cannot be resolved"
      + "\neINSTANCE cannot be resolved"
      + "\ndslNode_Domain cannot be resolved"
      + "\ndomain cannot be resolved");
  }
  
  @Check
  public void checkDslRoleNameStartsWithCapital(final /* DslRole */Object dslRole) {
    throw new Error("Unresolved compilation problems:"
      + "\nPuppetDslPackage.eINSTANCE cannot be resolved to a type."
      + "\nname cannot be resolved"
      + "\ncharAt cannot be resolved"
      + "\nupperCase cannot be resolved"
      + "\neINSTANCE cannot be resolved"
      + "\ndslRole_Name cannot be resolved"
      + "\nname cannot be resolved");
  }
}
