/**
 * Generated by Xgen. !!! DO NOT EDIT BY HAND IF THIS FILE WAS GENERATED TO A DERIVED DIRECTORY !!!
 * Xtend Template: org.xmdlab.cartridge.generator.dsl.templates.generator.CartridgeGeneratorXtendTpl
 */
package org.xmdlab.cartridge.rails.generator

/**
 * The RailsCartridgeGeneratorStandaloneSetup
 *
 * @author Sebastian Freund<seba1403@googlemail.com>
 *
 */
class RailsCartridgeGenerator extends RailsCartridgeGeneratorBase {

}
