/**
 * Generated by Xgen. !!! DO NOT EDIT BY HAND IF THIS FILE WAS GENERATED TO A DERIVED DIRECTORY !!!
 * Xtend Template: org.xmdlab.cartridge.generator.dsl.templates.metafacade.CartridgeMetafacadeBaseXtendTpl
 */
package org.xmdlab.cartridge.jee.metafacade

import org.xmdlab.cartridge.common.metafacade.MetafacadeBase
import org.xmdlab.jee.application.mm.MmApplication

abstract class ApplicationMetafacadeBase extends MetafacadeBase<MmApplication> implements ApplicationMetafacade {
}
