/**
 * Generated by Xgen. !!! DO NOT EDIT BY HAND IF THIS FILE WAS GENERATED TO A DERIVED DIRECTORY !!!
 * Xtend Template: org.xmdlab.cartridge.generator.dsl.templates.metafacade.CartridgeMetafacadeXtendTpl
 */
package org.xmdlab.cartridge.jee.metafacade

import org.xmdlab.cartridge.common.metafacade.Metafacade

interface EntityMetafacade extends Metafacade<org.xmdlab.jee.application.mm.MmEntity> {
}
