/**
 * Generated by Xgen. !!! DO NOT EDIT BY HAND IF THIS FILE WAS GENERATED TO A DERIVED DIRECTORY !!!
 * Xtend Template: org.xmdlab.cartridge.generator.dsl.templates.metafacade.CartridgeMetafacadeBaseXtendTpl
 */
package org.xmdlab.cartridge.jee.metafacade

import org.xmdlab.cartridge.common.metafacade.MetafacadeBase

abstract class EntityMetafacadeBase extends MetafacadeBase<org.xmdlab.jee.application.mm.Entity> implements EntityMetafacade {
}
