/*
* generated by Xtext
*/
package org.xmdlab.dsl.puppet;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class PuppetDslStandaloneSetup extends PuppetDslStandaloneSetupGenerated{

	public static void doSetup() {
		new PuppetDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

