/*
 * generated by Xtext
 */
package org.xmdlab.dsl.puppet;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PuppetDslRuntimeModule extends org.xmdlab.dsl.puppet.AbstractPuppetDslRuntimeModule {

}
