/**
 * generated by Xtext
 */
package org.xmdlab.dsl.puppet.formatting;

import com.google.inject.Inject;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.formatting.impl.AbstractDeclarativeFormatter;
import org.eclipse.xtext.formatting.impl.FormattingConfig;
import org.eclipse.xtext.xbase.lib.Extension;
import org.xmdlab.dsl.puppet.services.PuppetDslGrammarAccess;

/**
 * This class contains custom formatting description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#formatting
 * on how and when to use it
 * 
 * Also see {@link org.eclipse.xtext.xtext.XtextFormattingTokenSerializer} as an example
 */
@SuppressWarnings("all")
public class PuppetDslFormatter extends AbstractDeclarativeFormatter {
  @Inject
  @Extension
  private PuppetDslGrammarAccess g;
  
  protected void configureFormatting(final FormattingConfig c) {
    FormattingConfig.LinewrapLocator _setLinewrap = c.setLinewrap(0, 1, 2);
    TerminalRule _sL_COMMENTRule = this.g.getSL_COMMENTRule();
    _setLinewrap.before(_sL_COMMENTRule);
    FormattingConfig.LinewrapLocator _setLinewrap_1 = c.setLinewrap(0, 1, 2);
    TerminalRule _mL_COMMENTRule = this.g.getML_COMMENTRule();
    _setLinewrap_1.before(_mL_COMMENTRule);
    FormattingConfig.LinewrapLocator _setLinewrap_2 = c.setLinewrap(0, 1, 1);
    TerminalRule _mL_COMMENTRule_1 = this.g.getML_COMMENTRule();
    _setLinewrap_2.after(_mL_COMMENTRule_1);
    final PuppetDslGrammarAccess.DslNodeElements n = this.g.getDslNodeAccess();
    Keyword _leftCurlyBracketKeyword_5 = n.getLeftCurlyBracketKeyword_5();
    Keyword _rightCurlyBracketKeyword_7 = n.getRightCurlyBracketKeyword_7();
    c.setIndentation(_leftCurlyBracketKeyword_5, _rightCurlyBracketKeyword_7);
    FormattingConfig.LinewrapLocator _setLinewrap_3 = c.setLinewrap();
    Keyword _leftCurlyBracketKeyword_5_1 = n.getLeftCurlyBracketKeyword_5();
    _setLinewrap_3.after(_leftCurlyBracketKeyword_5_1);
    FormattingConfig.LinewrapLocator _setLinewrap_4 = c.setLinewrap(2);
    Keyword _rightCurlyBracketKeyword_7_1 = n.getRightCurlyBracketKeyword_7();
    _setLinewrap_4.after(_rightCurlyBracketKeyword_7_1);
    final PuppetDslGrammarAccess.DslRoleElements r = this.g.getDslRoleAccess();
    FormattingConfig.LinewrapLocator _setLinewrap_5 = c.setLinewrap();
    Keyword _leftCurlyBracketKeyword_2 = r.getLeftCurlyBracketKeyword_2();
    _setLinewrap_5.after(_leftCurlyBracketKeyword_2);
    FormattingConfig.LinewrapLocator _setLinewrap_6 = c.setLinewrap(1);
    Keyword _rightCurlyBracketKeyword_4 = r.getRightCurlyBracketKeyword_4();
    _setLinewrap_6.after(_rightCurlyBracketKeyword_4);
    Keyword _leftCurlyBracketKeyword_2_1 = r.getLeftCurlyBracketKeyword_2();
    Keyword _rightCurlyBracketKeyword_4_1 = r.getRightCurlyBracketKeyword_4();
    c.setIndentation(_leftCurlyBracketKeyword_2_1, _rightCurlyBracketKeyword_4_1);
    final PuppetDslGrammarAccess.DslProfileElements p = this.g.getDslProfileAccess();
    FormattingConfig.LinewrapLocator _setLinewrap_7 = c.setLinewrap();
    Keyword _leftCurlyBracketKeyword_2_2 = p.getLeftCurlyBracketKeyword_2();
    _setLinewrap_7.after(_leftCurlyBracketKeyword_2_2);
    FormattingConfig.LinewrapLocator _setLinewrap_8 = c.setLinewrap(1);
    Keyword _rightCurlyBracketKeyword_4_2 = p.getRightCurlyBracketKeyword_4();
    _setLinewrap_8.after(_rightCurlyBracketKeyword_4_2);
    Keyword _leftCurlyBracketKeyword_2_3 = p.getLeftCurlyBracketKeyword_2();
    Keyword _rightCurlyBracketKeyword_4_3 = p.getRightCurlyBracketKeyword_4();
    c.setIndentation(_leftCurlyBracketKeyword_2_3, _rightCurlyBracketKeyword_4_3);
  }
}
