/**
 * Generated by Xgen. !!! DO NOT EDIT BY HAND IF THIS FILE WAS GENERATED TO A DERIVED DIRECTORY !!!
 * Xtend Template: org.xmdlab.cartridge.jee.templates.EntityTpl
 */
package org.application.manager.organisation

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import org.xmdlab.framework.jee.domain.AbstractEntity;

/**
 * The org.xmdlab.cartridge.jee.templates.EntityTpl
 *
 * @author Sebastian Freund<seba1403@googlemail.com>
 *
 */
@Entity
@Table(name = "organisation")
public class Organisation extends AbstractEntity {
	
	/**
	 * Default constructor
	 */
	public Organisation() { }
	
	// no required constructor
	
	
	public String getName() {
		return name;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	public String getDescription() {
		return description;
	}
	
	public void setDescription(String description) {
		this.description = description;
	}
	
	@Override
	public String toString() {
		return "Organisation [id=" + getId()
			+ ", name=" + name
			+ ", description=" + description
			+ "]";
	}
	
	/**
	 * A Builder class used to create new Organisation objects.
	 */
	public static class Builder {
		Organisation built;
	
		/**
		 * Creates a new Builder instance.
		 * @param name 
		 * @param description 
		 */
		Builder(String name, String description) {
			built = new Organisation();
			built.name = name;
			built.description = description;
		}
	
		/**
		 * Builds the new Organisation object.
		 * @return  The created Organisation object.
		 */
		public Organisation build() {
			return built;
		}
	}
}
