/**
 * Generated by Xgen. !!! DO NOT EDIT BY HAND IF THIS FILE WAS GENERATED TO A DERIVED DIRECTORY !!!
 * Xtend Template: org.xmdlab.cartridge.generator.dsl.templates.metafacade.CartridgeMetafacadeImplXtendTpl
 */
package org.xmdlab.cartridge.rails.metafacade

import com.google.inject.Singleton

@Singleton
class ApplicationMetafacadeImpl extends ApplicationMetafacadeBase {

}
