/*
* generated by Xtext
*/
package org.xmdlab.dsl.puppet.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PuppetDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/xmdlab/dsl/puppet/parser/antlr/internal/InternalPuppetDsl.tokens");
	}
}
