/*
* generated by Xtext
*/
package org.xmdlab.dsl.puppet.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xmdlab.dsl.puppet.services.PuppetDslGrammarAccess;

public class PuppetDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private PuppetDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xmdlab.dsl.puppet.parser.antlr.internal.InternalPuppetDslParser createParser(XtextTokenStream stream) {
		return new org.xmdlab.dsl.puppet.parser.antlr.internal.InternalPuppetDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "DslModel";
	}
	
	public PuppetDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PuppetDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
