/*
 * generated by Xtext
 */
package org.xmdlab.dsl.application.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ApplicationDslUiModule extends org.xmdlab.dsl.application.ui.AbstractApplicationDslUiModule {
	public ApplicationDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
