/*
* generated by Xtext
*/
package org.xmdlab.dsl.domain;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class DomainDslStandaloneSetup extends DomainDslStandaloneSetupGenerated{

	public static void doSetup() {
		new DomainDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

