grammar org.xmdlab.dsl.domain.DomainDsl with org.eclipse.xtext.common.Terminals

generate domainDsl "http://www.xmdlab.org/dsl/domain/DomainDsl"

DslModel:
	domain=DslDomain
;

DslDomain:
	'Domain' name=QualifiedName '{'
		(nodes+=DslNode)*
	'}'
;

DslNode:
	(doc=STRING)?
	'Node' name=ID '{'
		role=DslRole
	'}'
;

DslRole:
	'Role' name=ID '{'
		
	'}'
;

QualifiedName:
  ID (=>'.' ID)*;
  
Version:
  ID (=>'.' ID) (=>'.' ID);
  
ForgeId:
  ID => '-' ID;