/*
 * generated by Xtext
 */
package org.xmdlab.dsl.domain;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DomainDslRuntimeModule extends org.xmdlab.dsl.domain.AbstractDomainDslRuntimeModule {

}
