/*
 * generated by Xtext
 */
package org.xmdlab.dsl.application.ui.contentassist

import org.xmdlab.dsl.application.ui.contentassist.AbstractApplicationDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ApplicationDslProposalProvider extends AbstractApplicationDslProposalProvider {
}
