/**
 * Generated by Xgen. !!! DO NOT EDIT BY HAND IF THIS FILE WAS GENERATED TO A DERIVED DIRECTORY !!!
 * Xtend Template: org.xmdlab.cartridge.generator.dsl.templates.templates.TemplateTpl
 */
package org.xmdlab.cartridge.jee.templates

class EntityTpl extends EntityTplBase {

	//	@Inject extension JeeCartridgeProperties
	override doGenerate() '''
		«val entity = entityMetafacade.modelResource»
		public class «entity.name» {
			
		}
	'''
}
