proxyUrl      = 'http://cartridge.conf:cartridge.conf'
noProxy       = 'localhost|127.0.0.1'

Vagrant.configure('2') do |config|
  # TODO Implement org.xmdlab.cartridge.puppet.templates.VagrantfileTpl:compileProxyConf
  
  config.vm.define "appserver" do |appserver|
    appserver.vm.box = "precise64"
    appserver.vm.box_url = "http://files.vagrantup.com/precise64.box"
    appserver.vm.network :forwarded_port, guest: 80, host: 8080
    appserver.vm.provision :puppet do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file  = "site.pp"
      puppet.module_path    = "modules"
    end
    config.vm.provision :shell, :inline => 'echo Visit http://appserver:8080/...'
  end
  
  config.vm.define "webserver" do |webserver|
    webserver.vm.box = "precise64"
    webserver.vm.box_url = "http://files.vagrantup.com/precise64.box"
    webserver.vm.network :forwarded_port, guest: 80, host: 8080
    webserver.vm.provision :puppet do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file  = "site.pp"
      puppet.module_path    = "modules"
    end
    config.vm.provision :shell, :inline => 'echo Visit http://webserver:8080/...'
  end
end	
