/**
 * Generated by Xgen. !!! DO NOT EDIT BY HAND IF THIS FILE WAS GENERATED TO A DERIVED DIRECTORY !!!
 * Xtend Template: org.xmdlab.cartridge.generator.dsl.templates.task.TaskClassTpl
 */
package org.xmdlab.cartridge.rails.task

import org.xmdlab.cartridge.common.task.Task

/**
*
*/
public class CreateInitialProjectTask implements Task {
	
	override run() {
		throw new UnsupportedOperationException("TODO: Implement CreateInitialProject.run()")
	}
}
