/**
 * Generated by Xgen. !!! DO NOT EDIT BY HAND IF THIS FILE WAS GENERATED TO A DERIVED DIRECTORY !!!
 * Xtend Template: org.xmdlab.cartridge.generator.dsl.templates.generator.CartridgeGeneratorModuleTpl
 */
package org.xmdlab.cartridge.jee;

import org.eclipse.xtext.generator.JavaIoFileSystemAccess;
import org.eclipse.xtext.service.AbstractGenericModule;
import org.xmdlab.cartridge.common.conf.CartridgeProperties;
import org.xmdlab.cartridge.common.generator.IOutputConfigurationProvider;
import org.xmdlab.cartridge.common.generator.JavaIoFileSystemAccessExt;
import org.xmdlab.cartridge.jee.conf.JeeCartridgeProperties;
import org.xmdlab.cartridge.jee.generator.JeeCartridgeGenerator;
import org.xmdlab.cartridge.jee.io.JeeCartridgeOutputConfigurationProvider;
import org.xmdlab.cartridge.jee.metafacade.*;

import com.google.inject.Binder;

/**
 * The JeeCartridgeGeneratorModule
 *
 * @author Sebastian Freund<seba1403@googlemail.com>
 *
 */
public class JeeCartridgeGeneratorModule extends AbstractGenericModule {

	@Override
	public void configure(Binder binder) {
		super.configure(binder);
	}
	
	public Class<? extends CartridgeProperties> bindJeeCartridgeProjectProperties() {
		return JeeCartridgeProperties.class;
	}
	
	public Class<? extends org.xmdlab.cartridge.common.generator.IGenerator> bindIGenerator() {
		return JeeCartridgeGenerator.class;
	}
	
	public Class<? extends IOutputConfigurationProvider> bindIOutputConfigurationProvider() {
		return JeeCartridgeOutputConfigurationProvider.class;
	}
	
	public Class<? extends JavaIoFileSystemAccess> bindJavaIoFileSystemAccess() {
		return JavaIoFileSystemAccessExt.class;
	}
	
	public Class<? extends ApplicationMetafacade> bindApplicationMetafacade() {
		return ApplicationMetafacadeImpl.class;
	}
	
	public Class<? extends EntityMetafacade> bindEntityMetafacade() {
		return EntityMetafacadeImpl.class;
	}
	
}
